// Generated by gencpp from file husky_follow_light/PerformActionResponse.msg
// DO NOT EDIT!


#ifndef HUSKY_FOLLOW_LIGHT_MESSAGE_PERFORMACTIONRESPONSE_H
#define HUSKY_FOLLOW_LIGHT_MESSAGE_PERFORMACTIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace husky_follow_light
{
template <class ContainerAllocator>
struct PerformActionResponse_
{
  typedef PerformActionResponse_<ContainerAllocator> Type;

  PerformActionResponse_()
    : success(false)  {
    }
  PerformActionResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::husky_follow_light::PerformActionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::husky_follow_light::PerformActionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PerformActionResponse_

typedef ::husky_follow_light::PerformActionResponse_<std::allocator<void> > PerformActionResponse;

typedef boost::shared_ptr< ::husky_follow_light::PerformActionResponse > PerformActionResponsePtr;
typedef boost::shared_ptr< ::husky_follow_light::PerformActionResponse const> PerformActionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::husky_follow_light::PerformActionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::husky_follow_light::PerformActionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::husky_follow_light::PerformActionResponse_<ContainerAllocator1> & lhs, const ::husky_follow_light::PerformActionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::husky_follow_light::PerformActionResponse_<ContainerAllocator1> & lhs, const ::husky_follow_light::PerformActionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace husky_follow_light

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::husky_follow_light::PerformActionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::husky_follow_light::PerformActionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::husky_follow_light::PerformActionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::husky_follow_light::PerformActionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::husky_follow_light::PerformActionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::husky_follow_light::PerformActionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::husky_follow_light::PerformActionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::husky_follow_light::PerformActionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::husky_follow_light::PerformActionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "husky_follow_light/PerformActionResponse";
  }

  static const char* value(const ::husky_follow_light::PerformActionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::husky_follow_light::PerformActionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
;
  }

  static const char* value(const ::husky_follow_light::PerformActionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::husky_follow_light::PerformActionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PerformActionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::husky_follow_light::PerformActionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::husky_follow_light::PerformActionResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HUSKY_FOLLOW_LIGHT_MESSAGE_PERFORMACTIONRESPONSE_H
