// Generated by gencpp from file husky_follow_light/PerformAction.msg
// DO NOT EDIT!


#ifndef HUSKY_FOLLOW_LIGHT_MESSAGE_PERFORMACTION_H
#define HUSKY_FOLLOW_LIGHT_MESSAGE_PERFORMACTION_H

#include <ros/service_traits.h>


#include <husky_follow_light/PerformActionRequest.h>
#include <husky_follow_light/PerformActionResponse.h>


namespace husky_follow_light
{

struct PerformAction
{

typedef PerformActionRequest Request;
typedef PerformActionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PerformAction
} // namespace husky_follow_light


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::husky_follow_light::PerformAction > {
  static const char* value()
  {
    return "02058b7d55716526fae62eb68abd6f31";
  }

  static const char* value(const ::husky_follow_light::PerformAction&) { return value(); }
};

template<>
struct DataType< ::husky_follow_light::PerformAction > {
  static const char* value()
  {
    return "husky_follow_light/PerformAction";
  }

  static const char* value(const ::husky_follow_light::PerformAction&) { return value(); }
};


// service_traits::MD5Sum< ::husky_follow_light::PerformActionRequest> should match
// service_traits::MD5Sum< ::husky_follow_light::PerformAction >
template<>
struct MD5Sum< ::husky_follow_light::PerformActionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::husky_follow_light::PerformAction >::value();
  }
  static const char* value(const ::husky_follow_light::PerformActionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::husky_follow_light::PerformActionRequest> should match
// service_traits::DataType< ::husky_follow_light::PerformAction >
template<>
struct DataType< ::husky_follow_light::PerformActionRequest>
{
  static const char* value()
  {
    return DataType< ::husky_follow_light::PerformAction >::value();
  }
  static const char* value(const ::husky_follow_light::PerformActionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::husky_follow_light::PerformActionResponse> should match
// service_traits::MD5Sum< ::husky_follow_light::PerformAction >
template<>
struct MD5Sum< ::husky_follow_light::PerformActionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::husky_follow_light::PerformAction >::value();
  }
  static const char* value(const ::husky_follow_light::PerformActionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::husky_follow_light::PerformActionResponse> should match
// service_traits::DataType< ::husky_follow_light::PerformAction >
template<>
struct DataType< ::husky_follow_light::PerformActionResponse>
{
  static const char* value()
  {
    return DataType< ::husky_follow_light::PerformAction >::value();
  }
  static const char* value(const ::husky_follow_light::PerformActionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HUSKY_FOLLOW_LIGHT_MESSAGE_PERFORMACTION_H
